name: webview_flutter_android
description: A Flutter plugin that provides a WebView widget on Android.
version: 2.7.0

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.22.0 <2.0.0"

flutter:
  plugin:
    implements: webview_flutter
    platforms:
      android:
        package: io.flutter.plugins.webviewflutter
        pluginClass: WebViewFlutterPlugin

dependencies:
  flutter:
    sdk: flutter
  webview_flutter_platform_interface:
    git:
      url: https://github.com/ankit-roy-greenway/webview_flutter_platform_interface.git
      ref: main

dev_dependencies:
  build_runner: ^1.11.1+1
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2
  pigeon: 0.1.23
